### ISSUE TITLE
Should a minimum `minInterval` be spec’ed?

### ISSUE THREAD

**Issue by tomayac** [beverloo/periodic-background-sync#15]
In practice, periodic syncs can’t happen too frequently, for example, Android [enforces 15min](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/recurring-work) and iOS [enforces 10min](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/SchedulingBackgroundActivity.html#//apple_ref/doc/uid/TP40013929-CH32-SW10) as minimum intervals. The spec might mention these values as orientation points.

**Comment by karx** [comment]
Rather we could have a section that helps make the decision on the frequency, by describing the performance impact of background sync.

**Comment by mugdhalakhani** [comment]
Updated the explainer to include recommendations that help decide an appropriate frequency. Closing this now, thanks!
